# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ABv2BQ71BvDhsykG7YHBbvFdM92IUUSO
"""

def add(x,y):
  return x+y

def substract(x,y):
  return x-y

def multiply(x,y):
  return x*y

def divide(x,y):
  return x/y

print("""Select operation:
1.Add
2.Substract
3.Multiply
4.Divide""")

while True:
  operation = input("Enter operation number you want to execute (1/2/3/4): ")

  if operation in ('1', '2', '3', '4'):
    try:
      num1 = float(input("Enter first number: "))
      num2 = float(input("Enter second number: "))
    except ValueError:
      print("Invalid input. Please enter a number.")
      continue

    if operation == '1':
      print(f'{num1} + {num2} = {add(num1, num2)}')
    if operation == '2':
      print(f'{num1} - {num2} = {substract(num1, num2)}')
    if operation == '3':
      print(f'{num1} * {num2} = {multiply(num1, num2)}')
    if operation == '4':
      print(f'{num1} / {num2} = {divide(num1, num2)}')

    next_operation = input("Do you want to perform another calculation? (Y/N): ")
    if next_operation == 'N':
      break
  else:
    print("Invalid input")